# Generated by Django 5.1.3 on 2024-12-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
    ]
